### ISSUE TITLE
minitest redshift QA is broken

### ISSUE THREAD

**Issue by weaverba137** [sbailey/desitest#5]
When I run the minitest notebook with release 18.3, in the Redshift QA section there is the equivalent of:
```python
from desisim.spec_qa import redshifts as dsq_z
assigned = zcat['TARGETID'] >= 0
dsq_z.match_truth_z(truth, zcat[assigned], mini_read=True)
```
which throws
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-53-5dcddf909781> in <module>()
      2 # match_truth_z fails on the repeated TARGETID=-1 of unassigned fibers, so filter those out
      3 assigned = zcat['TARGETID'] >= 0
----> 4 dsq_z.match_truth_z(truth, zcat[assigned], mini_read=True)

AttributeError: module 'desisim.spec_qa.redshifts' has no attribute 'match_truth_z'
```
The desisim version is 0.27.0.

**Comment by weaverba137** [comment]
In general, this brings up the question of tying the minitest notebook to particular releases.  I actually want to use a stable release, but development on the minitest does not appear to be tracking the stable releases.

**Comment by weaverba137** [comment]
Another problem:
```
bweaver@cori09[914]: desi_qa_s2n --qaprod_dir=/global/cscratch1/sd/bweaver/desi/dev/end2end/spectro/redux/mini/QA
usage: desi_qa_s2n [-h] [--qafig_path QAFIG_PATH]
desi_qa_s2n: error: unrecognized arguments: --qaprod_dir=/global/cscratch1/sd/bweaver/desi/dev/end2end/spectro/redux/mini/QA
```

**Comment by sbailey** [comment]
These are cases of the the minitest being *ahead* of 18.3 rather than *behind*.  It did highlight that I forgot to tag desitest with the version of the minitest notebook tested for 18.3.  I just made a retroactive tag of commit aee993a for 18.3 .

PR #2 and subsequent master commits https://github.com/desihub/desitest/commit/87ed6be4934eb811c111b9f7fa030250ea52f81a and https://github.com/desihub/desitest/commit/b851dec3ecca1ef61c2df74cf5beae408f047663 were for updates to the minitest notebook to work with current master of everything else.

If you need a copy that works with software release 18.3, you can use the desitest/18.3 tag, but beware that any changes are unlikely to merge well with master (version merging isn't a strong point of ipython notebooks...)

Side note: If this is for redshift DB tutorial prep, please prepare that as a separate notebook in the tutorials repo.  If you want to expand the current minitest notebook, please start with the master desi environment.

**Comment by weaverba137** [comment]
That's fine.  I'm not looking to merge changes right now.  I just wanted to *run* the minitest to produce a database based on loading from the zcatalog-mini.fits file, plus using the merged `desispec.database.redshift`.  It looks like in reference run 18.3, the database was never created.

Now that I have the database in hand, I'll create a separate notebook for the tutorial.

**Comment by sbailey** [comment]
I think this is the redshift database created by the 18.3 reference run:
`/project/projectdirs/desi/datachallenge/reference_runs/18.3/minitest.db` .  I'm not sure whether it was supposed to be there or down in `spectro/redux/mini/`.

**Comment by weaverba137** [comment]
Ah, that must be it.  Well, anyway, I did want to test a new way of loading it, so it was not a waste to recreate it.
